/**
 * Demo Synthetic Data Provider
 *
 * Provides realistic, sanitized, and de-identified mock healthcare datasets.
 * ALL DATA IN THIS FILE IS SYNTHETIC AND FABRICATED FOR ARCHITECTURAL TESTING.
 */

import { PCCFacility, PCCResident } from '@/pcc/types';
import { DMEOrder } from '@/dme/types';
import { IntegrationEvent } from '@/integration/types';

export const SYNTHETIC_FACILITIES: PCCFacility[] = [
  {
    facId: 'FAC-101',
    name: 'Pinecrest Rehabilitation & Healthcare',
    orgUuid: 'org-pcc-demo-snf-01',
    timeZone: 'America/Chicago',
    city: 'Oakbrook',
    state: 'IL',
    capacity: 120,
  },
  {
    facId: 'FAC-102',
    name: 'Meadowview Skilled Nursing Pavilion',
    orgUuid: 'org-pcc-demo-snf-01',
    timeZone: 'America/New_York',
    city: 'White Plains',
    state: 'NY',
    capacity: 95,
  },
  {
    facId: 'FAC-103',
    name: 'Harborview Transitional Care Center',
    orgUuid: 'org-pcc-demo-snf-02',
    timeZone: 'America/Los_Angeles',
    city: 'Bellevue',
    state: 'WA',
    capacity: 150,
  },
];

export const INITIAL_SYNTHETIC_FACILITIES = SYNTHETIC_FACILITIES;

export const INITIAL_SYNTHETIC_PCC_RESIDENTS: PCCResident[] = [
  {
    patientId: 'PCC-RES-88201',
    mrn: 'MRN-804192',
    facId: 'FAC-101',
    facilityName: 'Pinecrest Rehabilitation & Healthcare',
    firstName: 'Eleanor',
    lastName: 'Vance',
    gender: 'F',
    birthDate: '1942-05-14',
    admissionDate: '2026-08-10',
    roomNumber: '104',
    bedDescription: 'A (Window)',
    status: 'Active',
    primaryPayerName: 'Medicare Part A (Traditional)',
    primaryPayerType: 'Medicare',
    diagnoses: [
      {
        code: 'L89.153',
        description: 'Pressure ulcer of sacral region, stage 3',
        classification: 'Primary',
        onsetDate: '2026-08-12',
        rank: 1,
        isActive: true,
      },
      {
        code: 'E11.65',
        description: 'Type 2 diabetes mellitus with hyperglycemia',
        classification: 'Secondary',
        onsetDate: '2019-03-21',
        rank: 2,
        isActive: true,
      },
      {
        code: 'R29.6',
        description: 'Repeated falls, history of balance impairment',
        classification: 'Secondary',
        onsetDate: '2026-07-28',
        rank: 3,
        isActive: true,
      },
    ],
    lastModifiedTimestamp: '2026-09-22T14:30:00Z',
  },
  {
    patientId: 'PCC-RES-88202',
    mrn: 'MRN-492011',
    facId: 'FAC-101',
    facilityName: 'Pinecrest Rehabilitation & Healthcare',
    firstName: 'Arthur',
    lastName: 'Pendleton',
    gender: 'M',
    birthDate: '1938-11-03',
    admissionDate: '2026-09-01',
    roomNumber: '212',
    bedDescription: 'B (Door)',
    status: 'Active',
    primaryPayerName: 'Humana Gold Plus Medicare Advantage',
    primaryPayerType: 'Managed Care',
    diagnoses: [
      {
        code: 'J44.1',
        description: 'Chronic obstructive pulmonary disease with acute exacerbation',
        classification: 'Primary',
        onsetDate: '2026-08-30',
        rank: 1,
        isActive: true,
      },
      {
        code: 'I50.22',
        description: 'Chronic systolic (congestive) heart failure',
        classification: 'Secondary',
        onsetDate: '2022-04-15',
        rank: 2,
        isActive: true,
      },
    ],
    lastModifiedTimestamp: '2026-09-21T09:15:00Z',
  },
  {
    patientId: 'PCC-RES-88203',
    mrn: 'MRN-739104',
    facId: 'FAC-102',
    facilityName: 'Meadowview Skilled Nursing Pavilion',
    firstName: 'Clara',
    lastName: 'Olsen',
    gender: 'F',
    birthDate: '1947-02-19',
    admissionDate: '2026-08-28',
    roomNumber: '308',
    bedDescription: 'Private',
    status: 'Active',
    primaryPayerName: 'Blue Cross Blue Shield Senior Blue',
    primaryPayerType: 'Commercial',
    diagnoses: [
      {
        code: 'I69.351',
        description: 'Hemiplegia and hemiparesis following cerebral infarction',
        classification: 'Primary',
        onsetDate: '2026-08-15',
        rank: 1,
        isActive: true,
      },
      {
        code: 'G81.91',
        description: 'Hemiplegia, unspecified affecting right dominant side',
        classification: 'Secondary',
        onsetDate: '2026-08-15',
        rank: 2,
        isActive: true,
      },
    ],
    lastModifiedTimestamp: '2026-09-20T16:45:00Z',
  },
  {
    patientId: 'PCC-RES-88204',
    mrn: 'MRN-618492',
    facId: 'FAC-102',
    facilityName: 'Meadowview Skilled Nursing Pavilion',
    firstName: 'Marcus',
    lastName: 'Bennett',
    gender: 'M',
    birthDate: '1951-09-08',
    admissionDate: '2026-07-15',
    roomNumber: '115',
    bedDescription: 'A (Window)',
    status: 'Active',
    primaryPayerName: 'Illinois Medicaid LTC Program',
    primaryPayerType: 'Medicaid',
    diagnoses: [
      {
        code: 'M16.11',
        description: 'Unilateral primary osteoarthritis, right hip post-arthroplasty',
        classification: 'Primary',
        onsetDate: '2026-07-02',
        rank: 1,
        isActive: true,
      },
    ],
    lastModifiedTimestamp: '2026-09-19T11:00:00Z',
  },
  {
    patientId: 'PCC-RES-88205',
    mrn: 'MRN-551029',
    facId: 'FAC-103',
    facilityName: 'Harborview Transitional Care Center',
    firstName: 'Lydia',
    lastName: 'Kovacs',
    gender: 'F',
    birthDate: '1939-08-25',
    admissionDate: '2026-09-10',
    roomNumber: '402',
    bedDescription: 'Suite',
    status: 'Active',
    primaryPayerName: 'Aetna Medicare Prime Plan',
    primaryPayerType: 'Managed Care',
    diagnoses: [
      {
        code: 'G30.1',
        description: 'Alzheimer disease with late onset',
        classification: 'Primary',
        onsetDate: '2021-10-10',
        rank: 1,
        isActive: true,
      },
      {
        code: 'R29.6',
        description: 'Frequent fall risk, unsteadiness on feet',
        classification: 'Secondary',
        onsetDate: '2026-09-05',
        rank: 2,
        isActive: true,
      },
    ],
    lastModifiedTimestamp: '2026-09-22T08:00:00Z',
  },
];

export const INITIAL_SYNTHETIC_ORDERS: DMEOrder[] = [
  {
    orderId: 'ORD-2026-0901',
    mrn: 'MRN-804192',
    residentName: 'Vance, Eleanor',
    facilityName: 'Pinecrest Rehabilitation & Healthcare',
    room: '104-A',
    equipmentType: 'Alternating Pressure Mattress (Group 2 Low-Air-Loss)',
    category: 'Support Surfaces',
    orderDate: '2026-09-22T15:10:00Z',
    orderingUser: 'Dr. Sarah Lin, MD',
    orderingUserRole: 'Attending Physician',
    diagnosisIcd10: 'L89.153',
    diagnosisDescription: 'Pressure ulcer of sacral region, stage 3',
    status: 'DELIVERED',
    priority: 'URGENT',
    notes: 'Prescribed following stage 3 sacral breakdown identification.',
  },
  {
    orderId: 'ORD-2026-0902',
    mrn: 'MRN-492011',
    residentName: 'Pendleton, Arthur',
    facilityName: 'Pinecrest Rehabilitation & Healthcare',
    room: '212-B',
    equipmentType: 'Continuous Oxygen Concentrator (5L Stationary + Portable Backup)',
    category: 'Respiratory',
    orderDate: '2026-09-22T16:45:00Z',
    orderingUser: 'Nurse Karen Davis, RN',
    orderingUserRole: 'Clinical Nurse Specialist',
    diagnosisIcd10: 'J44.1',
    diagnosisDescription: 'COPD with acute exacerbation',
    status: 'DISPATCHED',
    priority: 'STAT',
    notes: 'Urgent titration required, maintain SpO2 > 90%.',
  },
  {
    orderId: 'ORD-2026-0903',
    mrn: 'MRN-739104',
    residentName: 'Olsen, Clara',
    facilityName: 'Meadowview Skilled Nursing Pavilion',
    room: '308-P',
    equipmentType: 'Full-Body Electric Patient Lift (Hoyer) with Commode Sling',
    category: 'Patient Handling',
    orderDate: '2026-09-23T08:20:00Z',
    orderingUser: 'Physical Therapist Mark Hall, DPT',
    orderingUserRole: 'Physical Therapist',
    diagnosisIcd10: 'I69.351',
    diagnosisDescription: 'Hemiplegia following cerebral infarction',
    status: 'APPROVED',
    priority: 'ROUTINE',
    notes: 'Required for safe chair transfers; resident unable to bear weight.',
  },
];

export const INITIAL_INTEGRATION_EVENTS: IntegrationEvent[] = [
  {
    id: 'evt-init-001',
    timestamp: '2026-09-23T07:45:12Z',
    provider: 'SYNTHETIC',
    eventType: 'PCC_PATIENT_SYNC',
    entityType: 'RESIDENT',
    entityId: 'BATCH',
    mrn: 'SYSTEM',
    source: 'SYNTHETIC',
    status: 'PROCESSED',
    duration: 42,
    processingTimeMs: 42,
    message: 'Synchronized 5 resident records across 3 facilities.',
    details: { facilities: ['FAC-101', 'FAC-102', 'FAC-103'], totalRecords: 5 },
  },
  {
    id: 'evt-init-002',
    timestamp: '2026-09-23T08:12:30Z',
    provider: 'SYNTHETIC',
    eventType: 'ADT_TRANSFER',
    entityType: 'RESIDENT',
    entityId: 'MRN-804192',
    mrn: 'MRN-804192',
    patientName: 'Vance, Eleanor',
    source: 'SYNTHETIC',
    status: 'PROCESSED',
    duration: 28,
    processingTimeMs: 28,
    message: 'Processed transfer to Room 104, Bed A.',
    details: { priorRoom: '102-B', newRoom: '104-A', facility: 'FAC-101' },
  },
  {
    id: 'evt-init-003',
    timestamp: '2026-09-23T08:21:05Z',
    provider: 'SYNTHETIC',
    eventType: 'DME_ORDER_CREATED',
    entityType: 'ORDER',
    entityId: 'ORD-2026-0903',
    mrn: 'MRN-739104',
    patientName: 'Olsen, Clara',
    source: 'SYNTHETIC',
    status: 'PROCESSED',
    duration: 35,
    processingTimeMs: 35,
    message: 'Created DME Order ORD-2026-0903 for Full-Body Electric Patient Lift.',
    details: { orderId: 'ORD-2026-0903', priority: 'ROUTINE' },
  },
];
